apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: frontend-namespace
spec:
  type: LoadBalancer
  loadBalancerIP: 104.154.45.67
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  
