apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.postgres.name }}-pv
spec:
  capacity:
    storage: {{ .Values.postgres.storage.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.postgres.name }}-pvc
  namespace: {{ .Values.postgres.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storage.size }}
  storageClassName: {{ .Values.postgres.pvc.storageClassName }}
