apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.name }}-secret
  namespace: {{ .Values.backend.namespace }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.backend.secret.DB_PASSWORD }}
